server:
  port: 8081
spring:
  application:
    name: projectServer
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: root
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://127.0.0.1:3306/mybooks?useUnicode=true&characterEncoding=UTF-8
    username: root
    validationQuery: SELECT 1 FROM DUAL
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 4000
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 8
      min-idle: 1
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.dlb.cloud.entity

logging:
  file: D:\logs\project.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread,%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{X-Span-Export:-}]
      %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread,%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{X-Span-Export:-}]
      %logger{15} - %msg%n'
       
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    UserService#saveUser():
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true # 把Eureka客户端的健康检测交个spring-boot-actuator模块的/health端点
  instance:
    lease-renewal-interval-in-seconds: 30 #服务续约任务的调用间隔时间
    lease-expiration-duration-in-seconds: 90 #服务失效的时间
